services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_PATH=/var/www/html/data/typing_test.db